//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace InventoryFeedService
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class IFSReportingEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new IFSReportingEntities object using the connection string found in the 'IFSReportingEntities' section of the application configuration file.
        /// </summary>
        public IFSReportingEntities() : base("name=IFSReportingEntities", "IFSReportingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IFSReportingEntities object.
        /// </summary>
        public IFSReportingEntities(string connectionString) : base(connectionString, "IFSReportingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new IFSReportingEntities object.
        /// </summary>
        public IFSReportingEntities(EntityConnection connection) : base(connection, "IFSReportingEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblInvoiceLinesMaster> tblInvoiceLinesMasters
        {
            get
            {
                if ((_tblInvoiceLinesMasters == null))
                {
                    _tblInvoiceLinesMasters = base.CreateObjectSet<tblInvoiceLinesMaster>("tblInvoiceLinesMasters");
                }
                return _tblInvoiceLinesMasters;
            }
        }
        private ObjectSet<tblInvoiceLinesMaster> _tblInvoiceLinesMasters;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblInvoiceLinesMasters EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblInvoiceLinesMasters(tblInvoiceLinesMaster tblInvoiceLinesMaster)
        {
            base.AddObject("tblInvoiceLinesMasters", tblInvoiceLinesMaster);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="IFSReportingModel", Name="tblInvoiceLinesMaster")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblInvoiceLinesMaster : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblInvoiceLinesMaster object.
        /// </summary>
        /// <param name="sTATISTIC_NO">Initial value of the STATISTIC_NO property.</param>
        public static tblInvoiceLinesMaster CreatetblInvoiceLinesMaster(global::System.Double sTATISTIC_NO)
        {
            tblInvoiceLinesMaster tblInvoiceLinesMaster = new tblInvoiceLinesMaster();
            tblInvoiceLinesMaster.STATISTIC_NO = sTATISTIC_NO;
            return tblInvoiceLinesMaster;
        }

        #endregion

        #region Simple Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Double STATISTIC_NO
        {
            get
            {
                return _STATISTIC_NO;
            }
            set
            {
                if (_STATISTIC_NO != value)
                {
                    OnSTATISTIC_NOChanging(value);
                    ReportPropertyChanging("STATISTIC_NO");
                    _STATISTIC_NO = StructuralObject.SetValidValue(value, "STATISTIC_NO");
                    ReportPropertyChanged("STATISTIC_NO");
                    OnSTATISTIC_NOChanged();
                }
            }
        }
        private global::System.Double _STATISTIC_NO;
        partial void OnSTATISTIC_NOChanging(global::System.Double value);
        partial void OnSTATISTIC_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> STATISTIC_DATE
        {
            get
            {
                return _STATISTIC_DATE;
            }
            set
            {
                OnSTATISTIC_DATEChanging(value);
                ReportPropertyChanging("STATISTIC_DATE");
                _STATISTIC_DATE = StructuralObject.SetValidValue(value, "STATISTIC_DATE");
                ReportPropertyChanged("STATISTIC_DATE");
                OnSTATISTIC_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _STATISTIC_DATE;
        partial void OnSTATISTIC_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnSTATISTIC_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> INVOICE_ID
        {
            get
            {
                return _INVOICE_ID;
            }
            set
            {
                OnINVOICE_IDChanging(value);
                ReportPropertyChanging("INVOICE_ID");
                _INVOICE_ID = StructuralObject.SetValidValue(value, "INVOICE_ID");
                ReportPropertyChanged("INVOICE_ID");
                OnINVOICE_IDChanged();
            }
        }
        private Nullable<global::System.Double> _INVOICE_ID;
        partial void OnINVOICE_IDChanging(Nullable<global::System.Double> value);
        partial void OnINVOICE_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ITEM_ID
        {
            get
            {
                return _ITEM_ID;
            }
            set
            {
                OnITEM_IDChanging(value);
                ReportPropertyChanging("ITEM_ID");
                _ITEM_ID = StructuralObject.SetValidValue(value, "ITEM_ID");
                ReportPropertyChanged("ITEM_ID");
                OnITEM_IDChanged();
            }
        }
        private Nullable<global::System.Double> _ITEM_ID;
        partial void OnITEM_IDChanging(Nullable<global::System.Double> value);
        partial void OnITEM_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> INVOICE_DATE
        {
            get
            {
                return _INVOICE_DATE;
            }
            set
            {
                OnINVOICE_DATEChanging(value);
                ReportPropertyChanging("INVOICE_DATE");
                _INVOICE_DATE = StructuralObject.SetValidValue(value, "INVOICE_DATE");
                ReportPropertyChanged("INVOICE_DATE");
                OnINVOICE_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _INVOICE_DATE;
        partial void OnINVOICE_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnINVOICE_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> INVOICED_QTY
        {
            get
            {
                return _INVOICED_QTY;
            }
            set
            {
                OnINVOICED_QTYChanging(value);
                ReportPropertyChanging("INVOICED_QTY");
                _INVOICED_QTY = StructuralObject.SetValidValue(value, "INVOICED_QTY");
                ReportPropertyChanged("INVOICED_QTY");
                OnINVOICED_QTYChanged();
            }
        }
        private Nullable<global::System.Double> _INVOICED_QTY;
        partial void OnINVOICED_QTYChanging(Nullable<global::System.Double> value);
        partial void OnINVOICED_QTYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> COST
        {
            get
            {
                return _COST;
            }
            set
            {
                OnCOSTChanging(value);
                ReportPropertyChanging("COST");
                _COST = StructuralObject.SetValidValue(value, "COST");
                ReportPropertyChanged("COST");
                OnCOSTChanged();
            }
        }
        private Nullable<global::System.Double> _COST;
        partial void OnCOSTChanging(Nullable<global::System.Double> value);
        partial void OnCOSTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SALE_UNIT_PRICE
        {
            get
            {
                return _SALE_UNIT_PRICE;
            }
            set
            {
                OnSALE_UNIT_PRICEChanging(value);
                ReportPropertyChanging("SALE_UNIT_PRICE");
                _SALE_UNIT_PRICE = StructuralObject.SetValidValue(value, "SALE_UNIT_PRICE");
                ReportPropertyChanged("SALE_UNIT_PRICE");
                OnSALE_UNIT_PRICEChanged();
            }
        }
        private Nullable<global::System.Double> _SALE_UNIT_PRICE;
        partial void OnSALE_UNIT_PRICEChanging(Nullable<global::System.Double> value);
        partial void OnSALE_UNIT_PRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> DISCOUNT
        {
            get
            {
                return _DISCOUNT;
            }
            set
            {
                OnDISCOUNTChanging(value);
                ReportPropertyChanging("DISCOUNT");
                _DISCOUNT = StructuralObject.SetValidValue(value, "DISCOUNT");
                ReportPropertyChanged("DISCOUNT");
                OnDISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _DISCOUNT;
        partial void OnDISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnDISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> BASE_SALE_UNIT_PRICE
        {
            get
            {
                return _BASE_SALE_UNIT_PRICE;
            }
            set
            {
                OnBASE_SALE_UNIT_PRICEChanging(value);
                ReportPropertyChanging("BASE_SALE_UNIT_PRICE");
                _BASE_SALE_UNIT_PRICE = StructuralObject.SetValidValue(value, "BASE_SALE_UNIT_PRICE");
                ReportPropertyChanged("BASE_SALE_UNIT_PRICE");
                OnBASE_SALE_UNIT_PRICEChanged();
            }
        }
        private Nullable<global::System.Double> _BASE_SALE_UNIT_PRICE;
        partial void OnBASE_SALE_UNIT_PRICEChanging(Nullable<global::System.Double> value);
        partial void OnBASE_SALE_UNIT_PRICEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> CURR_DISCOUNT
        {
            get
            {
                return _CURR_DISCOUNT;
            }
            set
            {
                OnCURR_DISCOUNTChanging(value);
                ReportPropertyChanging("CURR_DISCOUNT");
                _CURR_DISCOUNT = StructuralObject.SetValidValue(value, "CURR_DISCOUNT");
                ReportPropertyChanged("CURR_DISCOUNT");
                OnCURR_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _CURR_DISCOUNT;
        partial void OnCURR_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnCURR_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ORDER_DISCOUNT
        {
            get
            {
                return _ORDER_DISCOUNT;
            }
            set
            {
                OnORDER_DISCOUNTChanging(value);
                ReportPropertyChanging("ORDER_DISCOUNT");
                _ORDER_DISCOUNT = StructuralObject.SetValidValue(value, "ORDER_DISCOUNT");
                ReportPropertyChanged("ORDER_DISCOUNT");
                OnORDER_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _ORDER_DISCOUNT;
        partial void OnORDER_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnORDER_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ORDER_CURR_DISCOUNT
        {
            get
            {
                return _ORDER_CURR_DISCOUNT;
            }
            set
            {
                OnORDER_CURR_DISCOUNTChanging(value);
                ReportPropertyChanging("ORDER_CURR_DISCOUNT");
                _ORDER_CURR_DISCOUNT = StructuralObject.SetValidValue(value, "ORDER_CURR_DISCOUNT");
                ReportPropertyChanged("ORDER_CURR_DISCOUNT");
                OnORDER_CURR_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _ORDER_CURR_DISCOUNT;
        partial void OnORDER_CURR_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnORDER_CURR_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NET_AMOUNT
        {
            get
            {
                return _NET_AMOUNT;
            }
            set
            {
                OnNET_AMOUNTChanging(value);
                ReportPropertyChanging("NET_AMOUNT");
                _NET_AMOUNT = StructuralObject.SetValidValue(value, "NET_AMOUNT");
                ReportPropertyChanged("NET_AMOUNT");
                OnNET_AMOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _NET_AMOUNT;
        partial void OnNET_AMOUNTChanging(Nullable<global::System.Double> value);
        partial void OnNET_AMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> PRICE_QTY
        {
            get
            {
                return _PRICE_QTY;
            }
            set
            {
                OnPRICE_QTYChanging(value);
                ReportPropertyChanging("PRICE_QTY");
                _PRICE_QTY = StructuralObject.SetValidValue(value, "PRICE_QTY");
                ReportPropertyChanged("PRICE_QTY");
                OnPRICE_QTYChanged();
            }
        }
        private Nullable<global::System.Double> _PRICE_QTY;
        partial void OnPRICE_QTYChanging(Nullable<global::System.Double> value);
        partial void OnPRICE_QTYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> NET_CURR_AMOUNT
        {
            get
            {
                return _NET_CURR_AMOUNT;
            }
            set
            {
                OnNET_CURR_AMOUNTChanging(value);
                ReportPropertyChanging("NET_CURR_AMOUNT");
                _NET_CURR_AMOUNT = StructuralObject.SetValidValue(value, "NET_CURR_AMOUNT");
                ReportPropertyChanged("NET_CURR_AMOUNT");
                OnNET_CURR_AMOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _NET_CURR_AMOUNT;
        partial void OnNET_CURR_AMOUNTChanging(Nullable<global::System.Double> value);
        partial void OnNET_CURR_AMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GROSS_AMOUNT
        {
            get
            {
                return _GROSS_AMOUNT;
            }
            set
            {
                OnGROSS_AMOUNTChanging(value);
                ReportPropertyChanging("GROSS_AMOUNT");
                _GROSS_AMOUNT = StructuralObject.SetValidValue(value, "GROSS_AMOUNT");
                ReportPropertyChanged("GROSS_AMOUNT");
                OnGROSS_AMOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _GROSS_AMOUNT;
        partial void OnGROSS_AMOUNTChanging(Nullable<global::System.Double> value);
        partial void OnGROSS_AMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> GROSS_CURR_AMOUNT
        {
            get
            {
                return _GROSS_CURR_AMOUNT;
            }
            set
            {
                OnGROSS_CURR_AMOUNTChanging(value);
                ReportPropertyChanging("GROSS_CURR_AMOUNT");
                _GROSS_CURR_AMOUNT = StructuralObject.SetValidValue(value, "GROSS_CURR_AMOUNT");
                ReportPropertyChanged("GROSS_CURR_AMOUNT");
                OnGROSS_CURR_AMOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _GROSS_CURR_AMOUNT;
        partial void OnGROSS_CURR_AMOUNTChanging(Nullable<global::System.Double> value);
        partial void OnGROSS_CURR_AMOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CATALOG_DESC
        {
            get
            {
                return _CATALOG_DESC;
            }
            set
            {
                OnCATALOG_DESCChanging(value);
                ReportPropertyChanging("CATALOG_DESC");
                _CATALOG_DESC = StructuralObject.SetValidValue(value, true, "CATALOG_DESC");
                ReportPropertyChanged("CATALOG_DESC");
                OnCATALOG_DESCChanged();
            }
        }
        private global::System.String _CATALOG_DESC;
        partial void OnCATALOG_DESCChanging(global::System.String value);
        partial void OnCATALOG_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER_NAME
        {
            get
            {
                return _CUSTOMER_NAME;
            }
            set
            {
                OnCUSTOMER_NAMEChanging(value);
                ReportPropertyChanging("CUSTOMER_NAME");
                _CUSTOMER_NAME = StructuralObject.SetValidValue(value, true, "CUSTOMER_NAME");
                ReportPropertyChanged("CUSTOMER_NAME");
                OnCUSTOMER_NAMEChanged();
            }
        }
        private global::System.String _CUSTOMER_NAME;
        partial void OnCUSTOMER_NAMEChanging(global::System.String value);
        partial void OnCUSTOMER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNTRY_DESC
        {
            get
            {
                return _COUNTRY_DESC;
            }
            set
            {
                OnCOUNTRY_DESCChanging(value);
                ReportPropertyChanging("COUNTRY_DESC");
                _COUNTRY_DESC = StructuralObject.SetValidValue(value, true, "COUNTRY_DESC");
                ReportPropertyChanged("COUNTRY_DESC");
                OnCOUNTRY_DESCChanged();
            }
        }
        private global::System.String _COUNTRY_DESC;
        partial void OnCOUNTRY_DESCChanging(global::System.String value);
        partial void OnCOUNTRY_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUST_GRP_DESC
        {
            get
            {
                return _CUST_GRP_DESC;
            }
            set
            {
                OnCUST_GRP_DESCChanging(value);
                ReportPropertyChanging("CUST_GRP_DESC");
                _CUST_GRP_DESC = StructuralObject.SetValidValue(value, true, "CUST_GRP_DESC");
                ReportPropertyChanged("CUST_GRP_DESC");
                OnCUST_GRP_DESCChanged();
            }
        }
        private global::System.String _CUST_GRP_DESC;
        partial void OnCUST_GRP_DESCChanging(global::System.String value);
        partial void OnCUST_GRP_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMPANY_NAME
        {
            get
            {
                return _COMPANY_NAME;
            }
            set
            {
                OnCOMPANY_NAMEChanging(value);
                ReportPropertyChanging("COMPANY_NAME");
                _COMPANY_NAME = StructuralObject.SetValidValue(value, true, "COMPANY_NAME");
                ReportPropertyChanged("COMPANY_NAME");
                OnCOMPANY_NAMEChanged();
            }
        }
        private global::System.String _COMPANY_NAME;
        partial void OnCOMPANY_NAMEChanging(global::System.String value);
        partial void OnCOMPANY_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARKET_DESC
        {
            get
            {
                return _MARKET_DESC;
            }
            set
            {
                OnMARKET_DESCChanging(value);
                ReportPropertyChanging("MARKET_DESC");
                _MARKET_DESC = StructuralObject.SetValidValue(value, true, "MARKET_DESC");
                ReportPropertyChanged("MARKET_DESC");
                OnMARKET_DESCChanged();
            }
        }
        private global::System.String _MARKET_DESC;
        partial void OnMARKET_DESCChanging(global::System.String value);
        partial void OnMARKET_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REGION_DESC
        {
            get
            {
                return _REGION_DESC;
            }
            set
            {
                OnREGION_DESCChanging(value);
                ReportPropertyChanging("REGION_DESC");
                _REGION_DESC = StructuralObject.SetValidValue(value, true, "REGION_DESC");
                ReportPropertyChanged("REGION_DESC");
                OnREGION_DESCChanged();
            }
        }
        private global::System.String _REGION_DESC;
        partial void OnREGION_DESCChanging(global::System.String value);
        partial void OnREGION_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DISTRICT_DESC
        {
            get
            {
                return _DISTRICT_DESC;
            }
            set
            {
                OnDISTRICT_DESCChanging(value);
                ReportPropertyChanging("DISTRICT_DESC");
                _DISTRICT_DESC = StructuralObject.SetValidValue(value, true, "DISTRICT_DESC");
                ReportPropertyChanged("DISTRICT_DESC");
                OnDISTRICT_DESCChanged();
            }
        }
        private global::System.String _DISTRICT_DESC;
        partial void OnDISTRICT_DESCChanging(global::System.String value);
        partial void OnDISTRICT_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SALESMAN
        {
            get
            {
                return _SALESMAN;
            }
            set
            {
                OnSALESMANChanging(value);
                ReportPropertyChanging("SALESMAN");
                _SALESMAN = StructuralObject.SetValidValue(value, true, "SALESMAN");
                ReportPropertyChanged("SALESMAN");
                OnSALESMANChanged();
            }
        }
        private global::System.String _SALESMAN;
        partial void OnSALESMANChanging(global::System.String value);
        partial void OnSALESMANChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHORIZE_NAME
        {
            get
            {
                return _AUTHORIZE_NAME;
            }
            set
            {
                OnAUTHORIZE_NAMEChanging(value);
                ReportPropertyChanging("AUTHORIZE_NAME");
                _AUTHORIZE_NAME = StructuralObject.SetValidValue(value, true, "AUTHORIZE_NAME");
                ReportPropertyChanged("AUTHORIZE_NAME");
                OnAUTHORIZE_NAMEChanged();
            }
        }
        private global::System.String _AUTHORIZE_NAME;
        partial void OnAUTHORIZE_NAMEChanging(global::System.String value);
        partial void OnAUTHORIZE_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRICE_LIST_DESC
        {
            get
            {
                return _PRICE_LIST_DESC;
            }
            set
            {
                OnPRICE_LIST_DESCChanging(value);
                ReportPropertyChanging("PRICE_LIST_DESC");
                _PRICE_LIST_DESC = StructuralObject.SetValidValue(value, true, "PRICE_LIST_DESC");
                ReportPropertyChanged("PRICE_LIST_DESC");
                OnPRICE_LIST_DESCChanged();
            }
        }
        private global::System.String _PRICE_LIST_DESC;
        partial void OnPRICE_LIST_DESCChanging(global::System.String value);
        partial void OnPRICE_LIST_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDER_NO
        {
            get
            {
                return _ORDER_NO;
            }
            set
            {
                OnORDER_NOChanging(value);
                ReportPropertyChanging("ORDER_NO");
                _ORDER_NO = StructuralObject.SetValidValue(value, true, "ORDER_NO");
                ReportPropertyChanged("ORDER_NO");
                OnORDER_NOChanged();
            }
        }
        private global::System.String _ORDER_NO;
        partial void OnORDER_NOChanging(global::System.String value);
        partial void OnORDER_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CATALOG_GROUP_DESC
        {
            get
            {
                return _CATALOG_GROUP_DESC;
            }
            set
            {
                OnCATALOG_GROUP_DESCChanging(value);
                ReportPropertyChanging("CATALOG_GROUP_DESC");
                _CATALOG_GROUP_DESC = StructuralObject.SetValidValue(value, true, "CATALOG_GROUP_DESC");
                ReportPropertyChanged("CATALOG_GROUP_DESC");
                OnCATALOG_GROUP_DESCChanged();
            }
        }
        private global::System.String _CATALOG_GROUP_DESC;
        partial void OnCATALOG_GROUP_DESCChanging(global::System.String value);
        partial void OnCATALOG_GROUP_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER_NO
        {
            get
            {
                return _CUSTOMER_NO;
            }
            set
            {
                OnCUSTOMER_NOChanging(value);
                ReportPropertyChanging("CUSTOMER_NO");
                _CUSTOMER_NO = StructuralObject.SetValidValue(value, true, "CUSTOMER_NO");
                ReportPropertyChanged("CUSTOMER_NO");
                OnCUSTOMER_NOChanged();
            }
        }
        private global::System.String _CUSTOMER_NO;
        partial void OnCUSTOMER_NOChanging(global::System.String value);
        partial void OnCUSTOMER_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUST_GRP
        {
            get
            {
                return _CUST_GRP;
            }
            set
            {
                OnCUST_GRPChanging(value);
                ReportPropertyChanging("CUST_GRP");
                _CUST_GRP = StructuralObject.SetValidValue(value, true, "CUST_GRP");
                ReportPropertyChanged("CUST_GRP");
                OnCUST_GRPChanged();
            }
        }
        private global::System.String _CUST_GRP;
        partial void OnCUST_GRPChanging(global::System.String value);
        partial void OnCUST_GRPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONTRACT
        {
            get
            {
                return _CONTRACT;
            }
            set
            {
                OnCONTRACTChanging(value);
                ReportPropertyChanging("CONTRACT");
                _CONTRACT = StructuralObject.SetValidValue(value, true, "CONTRACT");
                ReportPropertyChanged("CONTRACT");
                OnCONTRACTChanged();
            }
        }
        private global::System.String _CONTRACT;
        partial void OnCONTRACTChanging(global::System.String value);
        partial void OnCONTRACTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CATALOG_NO
        {
            get
            {
                return _CATALOG_NO;
            }
            set
            {
                OnCATALOG_NOChanging(value);
                ReportPropertyChanging("CATALOG_NO");
                _CATALOG_NO = StructuralObject.SetValidValue(value, true, "CATALOG_NO");
                ReportPropertyChanged("CATALOG_NO");
                OnCATALOG_NOChanged();
            }
        }
        private global::System.String _CATALOG_NO;
        partial void OnCATALOG_NOChanging(global::System.String value);
        partial void OnCATALOG_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PART_NO
        {
            get
            {
                return _PART_NO;
            }
            set
            {
                OnPART_NOChanging(value);
                ReportPropertyChanging("PART_NO");
                _PART_NO = StructuralObject.SetValidValue(value, true, "PART_NO");
                ReportPropertyChanged("PART_NO");
                OnPART_NOChanged();
            }
        }
        private global::System.String _PART_NO;
        partial void OnPART_NOChanging(global::System.String value);
        partial void OnPART_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRICE_LIST_NO
        {
            get
            {
                return _PRICE_LIST_NO;
            }
            set
            {
                OnPRICE_LIST_NOChanging(value);
                ReportPropertyChanging("PRICE_LIST_NO");
                _PRICE_LIST_NO = StructuralObject.SetValidValue(value, true, "PRICE_LIST_NO");
                ReportPropertyChanged("PRICE_LIST_NO");
                OnPRICE_LIST_NOChanged();
            }
        }
        private global::System.String _PRICE_LIST_NO;
        partial void OnPRICE_LIST_NOChanging(global::System.String value);
        partial void OnPRICE_LIST_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String AUTHORIZE_CODE
        {
            get
            {
                return _AUTHORIZE_CODE;
            }
            set
            {
                OnAUTHORIZE_CODEChanging(value);
                ReportPropertyChanging("AUTHORIZE_CODE");
                _AUTHORIZE_CODE = StructuralObject.SetValidValue(value, true, "AUTHORIZE_CODE");
                ReportPropertyChanged("AUTHORIZE_CODE");
                OnAUTHORIZE_CODEChanged();
            }
        }
        private global::System.String _AUTHORIZE_CODE;
        partial void OnAUTHORIZE_CODEChanging(global::System.String value);
        partial void OnAUTHORIZE_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SALESMAN_CODE
        {
            get
            {
                return _SALESMAN_CODE;
            }
            set
            {
                OnSALESMAN_CODEChanging(value);
                ReportPropertyChanging("SALESMAN_CODE");
                _SALESMAN_CODE = StructuralObject.SetValidValue(value, true, "SALESMAN_CODE");
                ReportPropertyChanged("SALESMAN_CODE");
                OnSALESMAN_CODEChanged();
            }
        }
        private global::System.String _SALESMAN_CODE;
        partial void OnSALESMAN_CODEChanging(global::System.String value);
        partial void OnSALESMAN_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DISTRICT_CODE
        {
            get
            {
                return _DISTRICT_CODE;
            }
            set
            {
                OnDISTRICT_CODEChanging(value);
                ReportPropertyChanging("DISTRICT_CODE");
                _DISTRICT_CODE = StructuralObject.SetValidValue(value, true, "DISTRICT_CODE");
                ReportPropertyChanged("DISTRICT_CODE");
                OnDISTRICT_CODEChanged();
            }
        }
        private global::System.String _DISTRICT_CODE;
        partial void OnDISTRICT_CODEChanging(global::System.String value);
        partial void OnDISTRICT_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REGION_CODE
        {
            get
            {
                return _REGION_CODE;
            }
            set
            {
                OnREGION_CODEChanging(value);
                ReportPropertyChanging("REGION_CODE");
                _REGION_CODE = StructuralObject.SetValidValue(value, true, "REGION_CODE");
                ReportPropertyChanged("REGION_CODE");
                OnREGION_CODEChanged();
            }
        }
        private global::System.String _REGION_CODE;
        partial void OnREGION_CODEChanging(global::System.String value);
        partial void OnREGION_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MARKET_CODE
        {
            get
            {
                return _MARKET_CODE;
            }
            set
            {
                OnMARKET_CODEChanging(value);
                ReportPropertyChanging("MARKET_CODE");
                _MARKET_CODE = StructuralObject.SetValidValue(value, true, "MARKET_CODE");
                ReportPropertyChanged("MARKET_CODE");
                OnMARKET_CODEChanged();
            }
        }
        private global::System.String _MARKET_CODE;
        partial void OnMARKET_CODEChanging(global::System.String value);
        partial void OnMARKET_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COMPANY
        {
            get
            {
                return _COMPANY;
            }
            set
            {
                OnCOMPANYChanging(value);
                ReportPropertyChanging("COMPANY");
                _COMPANY = StructuralObject.SetValidValue(value, true, "COMPANY");
                ReportPropertyChanged("COMPANY");
                OnCOMPANYChanged();
            }
        }
        private global::System.String _COMPANY;
        partial void OnCOMPANYChanging(global::System.String value);
        partial void OnCOMPANYChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SALES_UNIT_MEAS
        {
            get
            {
                return _SALES_UNIT_MEAS;
            }
            set
            {
                OnSALES_UNIT_MEASChanging(value);
                ReportPropertyChanging("SALES_UNIT_MEAS");
                _SALES_UNIT_MEAS = StructuralObject.SetValidValue(value, true, "SALES_UNIT_MEAS");
                ReportPropertyChanged("SALES_UNIT_MEAS");
                OnSALES_UNIT_MEASChanged();
            }
        }
        private global::System.String _SALES_UNIT_MEAS;
        partial void OnSALES_UNIT_MEASChanging(global::System.String value);
        partial void OnSALES_UNIT_MEASChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PRICE_UNIT_MEAS
        {
            get
            {
                return _PRICE_UNIT_MEAS;
            }
            set
            {
                OnPRICE_UNIT_MEASChanging(value);
                ReportPropertyChanging("PRICE_UNIT_MEAS");
                _PRICE_UNIT_MEAS = StructuralObject.SetValidValue(value, true, "PRICE_UNIT_MEAS");
                ReportPropertyChanged("PRICE_UNIT_MEAS");
                OnPRICE_UNIT_MEASChanged();
            }
        }
        private global::System.String _PRICE_UNIT_MEAS;
        partial void OnPRICE_UNIT_MEASChanging(global::System.String value);
        partial void OnPRICE_UNIT_MEASChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ACCT_CURRENCY_CODE
        {
            get
            {
                return _ACCT_CURRENCY_CODE;
            }
            set
            {
                OnACCT_CURRENCY_CODEChanging(value);
                ReportPropertyChanging("ACCT_CURRENCY_CODE");
                _ACCT_CURRENCY_CODE = StructuralObject.SetValidValue(value, true, "ACCT_CURRENCY_CODE");
                ReportPropertyChanged("ACCT_CURRENCY_CODE");
                OnACCT_CURRENCY_CODEChanged();
            }
        }
        private global::System.String _ACCT_CURRENCY_CODE;
        partial void OnACCT_CURRENCY_CODEChanging(global::System.String value);
        partial void OnACCT_CURRENCY_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ORDER_CURRENCY_CODE
        {
            get
            {
                return _ORDER_CURRENCY_CODE;
            }
            set
            {
                OnORDER_CURRENCY_CODEChanging(value);
                ReportPropertyChanging("ORDER_CURRENCY_CODE");
                _ORDER_CURRENCY_CODE = StructuralObject.SetValidValue(value, true, "ORDER_CURRENCY_CODE");
                ReportPropertyChanged("ORDER_CURRENCY_CODE");
                OnORDER_CURRENCY_CODEChanged();
            }
        }
        private global::System.String _ORDER_CURRENCY_CODE;
        partial void OnORDER_CURRENCY_CODEChanging(global::System.String value);
        partial void OnORDER_CURRENCY_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String COUNTRY_CODE
        {
            get
            {
                return _COUNTRY_CODE;
            }
            set
            {
                OnCOUNTRY_CODEChanging(value);
                ReportPropertyChanging("COUNTRY_CODE");
                _COUNTRY_CODE = StructuralObject.SetValidValue(value, true, "COUNTRY_CODE");
                ReportPropertyChanged("COUNTRY_CODE");
                OnCOUNTRY_CODEChanged();
            }
        }
        private global::System.String _COUNTRY_CODE;
        partial void OnCOUNTRY_CODEChanging(global::System.String value);
        partial void OnCOUNTRY_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CATALOG_GROUP
        {
            get
            {
                return _CATALOG_GROUP;
            }
            set
            {
                OnCATALOG_GROUPChanging(value);
                ReportPropertyChanging("CATALOG_GROUP");
                _CATALOG_GROUP = StructuralObject.SetValidValue(value, true, "CATALOG_GROUP");
                ReportPropertyChanged("CATALOG_GROUP");
                OnCATALOG_GROUPChanged();
            }
        }
        private global::System.String _CATALOG_GROUP;
        partial void OnCATALOG_GROUPChanging(global::System.String value);
        partial void OnCATALOG_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PART_DESC
        {
            get
            {
                return _PART_DESC;
            }
            set
            {
                OnPART_DESCChanging(value);
                ReportPropertyChanging("PART_DESC");
                _PART_DESC = StructuralObject.SetValidValue(value, true, "PART_DESC");
                ReportPropertyChanged("PART_DESC");
                OnPART_DESCChanged();
            }
        }
        private global::System.String _PART_DESC;
        partial void OnPART_DESCChanging(global::System.String value);
        partial void OnPART_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LINE_NO
        {
            get
            {
                return _LINE_NO;
            }
            set
            {
                OnLINE_NOChanging(value);
                ReportPropertyChanging("LINE_NO");
                _LINE_NO = StructuralObject.SetValidValue(value, true, "LINE_NO");
                ReportPropertyChanged("LINE_NO");
                OnLINE_NOChanged();
            }
        }
        private global::System.String _LINE_NO;
        partial void OnLINE_NOChanging(global::System.String value);
        partial void OnLINE_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String REL_NO
        {
            get
            {
                return _REL_NO;
            }
            set
            {
                OnREL_NOChanging(value);
                ReportPropertyChanging("REL_NO");
                _REL_NO = StructuralObject.SetValidValue(value, true, "REL_NO");
                ReportPropertyChanged("REL_NO");
                OnREL_NOChanged();
            }
        }
        private global::System.String _REL_NO;
        partial void OnREL_NOChanging(global::System.String value);
        partial void OnREL_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> LINE_ITEM_NO
        {
            get
            {
                return _LINE_ITEM_NO;
            }
            set
            {
                OnLINE_ITEM_NOChanging(value);
                ReportPropertyChanging("LINE_ITEM_NO");
                _LINE_ITEM_NO = StructuralObject.SetValidValue(value, "LINE_ITEM_NO");
                ReportPropertyChanged("LINE_ITEM_NO");
                OnLINE_ITEM_NOChanged();
            }
        }
        private Nullable<global::System.Double> _LINE_ITEM_NO;
        partial void OnLINE_ITEM_NOChanging(Nullable<global::System.Double> value);
        partial void OnLINE_ITEM_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYER_NO
        {
            get
            {
                return _PAYER_NO;
            }
            set
            {
                OnPAYER_NOChanging(value);
                ReportPropertyChanging("PAYER_NO");
                _PAYER_NO = StructuralObject.SetValidValue(value, true, "PAYER_NO");
                ReportPropertyChanged("PAYER_NO");
                OnPAYER_NOChanged();
            }
        }
        private global::System.String _PAYER_NO;
        partial void OnPAYER_NOChanging(global::System.String value);
        partial void OnPAYER_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String PAYER_NAME
        {
            get
            {
                return _PAYER_NAME;
            }
            set
            {
                OnPAYER_NAMEChanging(value);
                ReportPropertyChanging("PAYER_NAME");
                _PAYER_NAME = StructuralObject.SetValidValue(value, true, "PAYER_NAME");
                ReportPropertyChanged("PAYER_NAME");
                OnPAYER_NAMEChanged();
            }
        }
        private global::System.String _PAYER_NAME;
        partial void OnPAYER_NAMEChanging(global::System.String value);
        partial void OnPAYER_NAMEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER_PRICE_GROUP
        {
            get
            {
                return _CUSTOMER_PRICE_GROUP;
            }
            set
            {
                OnCUSTOMER_PRICE_GROUPChanging(value);
                ReportPropertyChanging("CUSTOMER_PRICE_GROUP");
                _CUSTOMER_PRICE_GROUP = StructuralObject.SetValidValue(value, true, "CUSTOMER_PRICE_GROUP");
                ReportPropertyChanged("CUSTOMER_PRICE_GROUP");
                OnCUSTOMER_PRICE_GROUPChanged();
            }
        }
        private global::System.String _CUSTOMER_PRICE_GROUP;
        partial void OnCUSTOMER_PRICE_GROUPChanging(global::System.String value);
        partial void OnCUSTOMER_PRICE_GROUPChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CUSTOMER_PRICE_GRP_DESC
        {
            get
            {
                return _CUSTOMER_PRICE_GRP_DESC;
            }
            set
            {
                OnCUSTOMER_PRICE_GRP_DESCChanging(value);
                ReportPropertyChanging("CUSTOMER_PRICE_GRP_DESC");
                _CUSTOMER_PRICE_GRP_DESC = StructuralObject.SetValidValue(value, true, "CUSTOMER_PRICE_GRP_DESC");
                ReportPropertyChanged("CUSTOMER_PRICE_GRP_DESC");
                OnCUSTOMER_PRICE_GRP_DESCChanged();
            }
        }
        private global::System.String _CUSTOMER_PRICE_GRP_DESC;
        partial void OnCUSTOMER_PRICE_GRP_DESCChanging(global::System.String value);
        partial void OnCUSTOMER_PRICE_GRP_DESCChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ADDITIONAL_DISCOUNT
        {
            get
            {
                return _ADDITIONAL_DISCOUNT;
            }
            set
            {
                OnADDITIONAL_DISCOUNTChanging(value);
                ReportPropertyChanging("ADDITIONAL_DISCOUNT");
                _ADDITIONAL_DISCOUNT = StructuralObject.SetValidValue(value, "ADDITIONAL_DISCOUNT");
                ReportPropertyChanged("ADDITIONAL_DISCOUNT");
                OnADDITIONAL_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _ADDITIONAL_DISCOUNT;
        partial void OnADDITIONAL_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnADDITIONAL_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> ADDITIONAL_CURR_DISCOUNT
        {
            get
            {
                return _ADDITIONAL_CURR_DISCOUNT;
            }
            set
            {
                OnADDITIONAL_CURR_DISCOUNTChanging(value);
                ReportPropertyChanging("ADDITIONAL_CURR_DISCOUNT");
                _ADDITIONAL_CURR_DISCOUNT = StructuralObject.SetValidValue(value, "ADDITIONAL_CURR_DISCOUNT");
                ReportPropertyChanged("ADDITIONAL_CURR_DISCOUNT");
                OnADDITIONAL_CURR_DISCOUNTChanged();
            }
        }
        private Nullable<global::System.Double> _ADDITIONAL_CURR_DISCOUNT;
        partial void OnADDITIONAL_CURR_DISCOUNTChanging(Nullable<global::System.Double> value);
        partial void OnADDITIONAL_CURR_DISCOUNTChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String BRANCH
        {
            get
            {
                return _BRANCH;
            }
            set
            {
                OnBRANCHChanging(value);
                ReportPropertyChanging("BRANCH");
                _BRANCH = StructuralObject.SetValidValue(value, true, "BRANCH");
                ReportPropertyChanged("BRANCH");
                OnBRANCHChanged();
            }
        }
        private global::System.String _BRANCH;
        partial void OnBRANCHChanging(global::System.String value);
        partial void OnBRANCHChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> CREATION_DATE
        {
            get
            {
                return _CREATION_DATE;
            }
            set
            {
                OnCREATION_DATEChanging(value);
                ReportPropertyChanging("CREATION_DATE");
                _CREATION_DATE = StructuralObject.SetValidValue(value, "CREATION_DATE");
                ReportPropertyChanged("CREATION_DATE");
                OnCREATION_DATEChanged();
            }
        }
        private Nullable<global::System.DateTime> _CREATION_DATE;
        partial void OnCREATION_DATEChanging(Nullable<global::System.DateTime> value);
        partial void OnCREATION_DATEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String INVOICE_NO
        {
            get
            {
                return _INVOICE_NO;
            }
            set
            {
                OnINVOICE_NOChanging(value);
                ReportPropertyChanging("INVOICE_NO");
                _INVOICE_NO = StructuralObject.SetValidValue(value, true, "INVOICE_NO");
                ReportPropertyChanged("INVOICE_NO");
                OnINVOICE_NOChanged();
            }
        }
        private global::System.String _INVOICE_NO;
        partial void OnINVOICE_NOChanging(global::System.String value);
        partial void OnINVOICE_NOChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SERIES_ID
        {
            get
            {
                return _SERIES_ID;
            }
            set
            {
                OnSERIES_IDChanging(value);
                ReportPropertyChanging("SERIES_ID");
                _SERIES_ID = StructuralObject.SetValidValue(value, true, "SERIES_ID");
                ReportPropertyChanged("SERIES_ID");
                OnSERIES_IDChanged();
            }
        }
        private global::System.String _SERIES_ID;
        partial void OnSERIES_IDChanging(global::System.String value);
        partial void OnSERIES_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONDITION_CODE
        {
            get
            {
                return _CONDITION_CODE;
            }
            set
            {
                OnCONDITION_CODEChanging(value);
                ReportPropertyChanging("CONDITION_CODE");
                _CONDITION_CODE = StructuralObject.SetValidValue(value, true, "CONDITION_CODE");
                ReportPropertyChanged("CONDITION_CODE");
                OnCONDITION_CODEChanged();
            }
        }
        private global::System.String _CONDITION_CODE;
        partial void OnCONDITION_CODEChanging(global::System.String value);
        partial void OnCONDITION_CODEChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String CONDITION_CODE_DESCRIPTION
        {
            get
            {
                return _CONDITION_CODE_DESCRIPTION;
            }
            set
            {
                OnCONDITION_CODE_DESCRIPTIONChanging(value);
                ReportPropertyChanging("CONDITION_CODE_DESCRIPTION");
                _CONDITION_CODE_DESCRIPTION = StructuralObject.SetValidValue(value, true, "CONDITION_CODE_DESCRIPTION");
                ReportPropertyChanged("CONDITION_CODE_DESCRIPTION");
                OnCONDITION_CODE_DESCRIPTIONChanged();
            }
        }
        private global::System.String _CONDITION_CODE_DESCRIPTION;
        partial void OnCONDITION_CODE_DESCRIPTIONChanging(global::System.String value);
        partial void OnCONDITION_CODE_DESCRIPTIONChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OBJID
        {
            get
            {
                return _OBJID;
            }
            set
            {
                OnOBJIDChanging(value);
                ReportPropertyChanging("OBJID");
                _OBJID = StructuralObject.SetValidValue(value, true, "OBJID");
                ReportPropertyChanged("OBJID");
                OnOBJIDChanged();
            }
        }
        private global::System.String _OBJID;
        partial void OnOBJIDChanging(global::System.String value);
        partial void OnOBJIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OBJVERSION
        {
            get
            {
                return _OBJVERSION;
            }
            set
            {
                OnOBJVERSIONChanging(value);
                ReportPropertyChanging("OBJVERSION");
                _OBJVERSION = StructuralObject.SetValidValue(value, true, "OBJVERSION");
                ReportPropertyChanged("OBJVERSION");
                OnOBJVERSIONChanged();
            }
        }
        private global::System.String _OBJVERSION;
        partial void OnOBJVERSIONChanging(global::System.String value);
        partial void OnOBJVERSIONChanged();

        #endregion

    }

    #endregion

}
